use tidyverse image

diff --git a/.github/workflows/singularity.yml b/.github/workflows/singularity.yml
--- a/.github/workflows/singularity.yml
+++ b/.github/workflows/singularity.yml
@@ -7,6 +7,8 @@ jobs:
     runs-on: ubuntu-18.04
     strategy:
       fail-fast: false
+      matrix:
+        recipe: ["Singularity"]
     steps:
 
     - name: Set up Go 1.12
@@ -40,16 +42,46 @@ jobs:
         cd singularity && \
         ./mconfig -p /usr/local && \
         make -C builddir && \
-        sudo make -C builddir install
-        rm -rf .singularity/
-    
+        sudo make -C builddir install          
+          
     - name: Check out code for the container build
       uses: actions/checkout@v1
 
-    - name: Pull Container
+    - name: Build Container
+      env:
+        SINGULARITY_RECIPE: ${{ matrix.recipe }}
+        OUTPUT_CONTAINER: container-${{ matrix.recipe }}.sif
       run: |
-       singularity pull --name container.sif shub://tpall/geo-htseq-paper
-
-    - name: Test Container
+       ls 
+       if [ -f "${SINGULARITY_RECIPE}" ]; then
+            sudo -E singularity build ${OUTPUT_CONTAINER} ${SINGULARITY_RECIPE}
+       else
+           echo "${SINGULARITY_RECIPE} is not found."
+           echo "Present working directory: $PWD"
+           ls
+       fi
+       ls
+       pwd
+    
+    - name: Test
+      env:
+        SINGULARITY_IMAGE: container-${{ matrix.recipe }}.sif
       run: |
-       singularity exec container.sif Rscript -e 'library("rstan"); example(stan_model, package = "rstan", run.dontrun = TRUE)'
+        echo "Using Singularity image: ${SINGULARITY_IMAGE}"
+        
+        version () {
+          singularity inspect "${SINGULARITY_IMAGE}" | \
+            grep "R_V" | \
+            awk -F' ' '{print $2}'
+        }
+        
+        set -e
+        set -x
+        
+        # Verify R version
+        singularity exec ${SINGULARITY_IMAGE} r -q -e "stopifnot(getRversion() == '$(version)')"
+        
+        # Test rstan
+        singularity exec ${SINGULARITY_IMAGE} r -e 'library(rstan); example(stan_model, package = "rstan", run.dontrun = TRUE)'
+        { set +x; } 2>/dev/null
+        echo "All tests passed!"
